#!/usr/bin/env bash

CFGDIR=/etc/selfy

function print_usage_and_exit {
		>&2 echo "usage: $0 [OPTIONS] <ANSIBLE-PLAYBOOK ARGS>"
		>&2 echo " where OPTIONS may be:"
		>&2 echo "  --office"
		>&2 echo "    Install packages to setup a basic office environment."
		>&2 echo "  --programming"
		>&2 echo "    Install packages to setup a basic computer programming (not web) environment."
		>&2 echo "  --webdev"
		>&2 echo "    Install packages to setup a basic web development environment."
		>&2 echo "  <ANSIBLE-PLAYBOOK ARGS> [Optional]"
		>&2 echo "     All arguments accepted by ansible-playbook command."
		>&2 echo "  --setup"
		>&2 echo "    Setup the environment to execute $0."
		exit 1
}

if [ "$#" -eq 0 ];
then
	print_usage_and_exit
fi

case $1 in
	--programming)
		shift
		ansible-playbook ${CFGDIR}/programming.yml $@
		;;
	--office)
		shift
		ansible-playbook ${CFGDIR}/office.yml $@
		;;
	--webdev)
		shift
		ansible-playbook ${CFGDIR}/programming.yml --extra-vars "is_webdev_env=True" $@
		;;
	*)
		shift
		print_usage_and_exit
		;;
esac

exit 0

