---
- name: add gpg key
  shell: wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
  tags: googlechrome

- name: include repository into sources.list.d
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
  tags: googlechrome

- name: install
  apt: 
    name: 'google-chrome-stable'
  tags: googlechrome

