- name: install interpreter and tools
  apt: 
    name: "{{ item }}"
  loop:
    - python3
    - python3-dev
    - python3-igraph
    - python3-matplotlib
    - python3-scipy
    - jupyter
    - virtualenv
  tags: python3

- name: include tasks for {{ ansible_os_family }} family
  include_tasks: "{{ ansible_os_family }}_family.yml"
  tags: python3
