---
- debug:
    msg: 
      - 'Documentation'
      - 'pytrainer - https://github.com/pytrainer/pytrainer'
      - 'workrave - https://workrave.org/docs/'
  tags: health

- name: install packages
  package:
    name: "{{ item }}"
  loop:
    - pytrainer
    - workrave
  tags: health

