---
- name: install programs to view images
  package:
    name: "{{ item }}"
  loop:
    - feh
    - imagemagick
    - sxiv
  tags: terminal
   
- name: install program(s) to manage files
  package:
    name: "{{ item }}" 
  loop:
    - mc
    - ranger
  tags: terminal

