---
- name: install major mode(s) for programming environment
  apt:
    name: "{{ item }}"
  loop:
    - golang-mode
    - elpa-haskell-mode
    - elpa-helm
    - elpa-lua-mode
    - elpa-magit
    - elpa-markdown-mode
    - elpa-org
    - elpa-projectile
    - elpa-rtags
    - elpa-rust-mode
    - elpa-scala-mode
    - elpa-yaml-mode
    - elpa-yasnippet
    - rtags
  tags: emacs

- name: install major mode(s) for webdev environment
  apt:
    name: "{{ item }}"
  loop:
    - elpa-js2-mode
    - elpa-php-mode
    - elpa-web-mode
  when: is_webdev_env is defined and is_webdev_env
  tags: emacs
